# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoMonUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 541)
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSearch = QtWidgets.QPushButton(self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(290, 20, 81, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.lbMonIMG = QtWidgets.QLabel(self.centralwidget)
        self.lbMonIMG.setGeometry(QtCore.QRect(520, 20, 211, 21))
        self.lbMonIMG.setText("")
        self.lbMonIMG.setObjectName("lbMonIMG")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 240, 71, 21))
        self.label_2.setObjectName("label_2")
        self.lwAutoFill = QtWidgets.QListWidget(self.centralwidget)
        self.lwAutoFill.setGeometry(QtCore.QRect(20, 60, 256, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lwAutoFill.setFont(font)
        self.lwAutoFill.setObjectName("lwAutoFill")
        self.lwFarmList = QtWidgets.QListWidget(self.centralwidget)
        self.lwFarmList.setGeometry(QtCore.QRect(20, 140, 256, 192))
        self.lwFarmList.setObjectName("lwFarmList")
        self.leMonSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.leMonSearch.setGeometry(QtCore.QRect(20, 20, 256, 31))
        self.leMonSearch.setObjectName("leMonSearch")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 60, 137, 50))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbLoadNew = QtWidgets.QRadioButton(self.widget)
        self.rbLoadNew.setChecked(True)
        self.rbLoadNew.setObjectName("rbLoadNew")
        self.verticalLayout.addWidget(self.rbLoadNew)
        self.rbLoadOld = QtWidgets.QRadioButton(self.widget)
        self.rbLoadOld.setObjectName("rbLoadOld")
        self.verticalLayout.addWidget(self.rbLoadOld)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSearch.setText(_translate("MainWindow", "검색"))
        self.label_2.setText(_translate("MainWindow", "몬스터 사진"))
        self.rbLoadNew.setText(_translate("MainWindow", "목록 갱신"))
        self.rbLoadOld.setText(_translate("MainWindow", "신규 농장 찾기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
